/**
 * Wardrobecare Clothing — Database Seed
 * Seeds real catalogue categories and curated premium products.
 * All prices in NGN, calibrated to typical Nigerian premium men's fashion.
 */
import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const db = new PrismaClient()

// Curated image references — Unsplash CDN. These are placeholders structured
// for easy replacement with real Wardrobecare product photography.
const IMG = {
  heroEditorial: 'https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?q=80&w=2000&auto=format&fit=crop',
  heroFashion: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?q=80&w=2000&auto=format&fit=crop',
  editorialMan: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?q=80&w=2000&auto=format&fit=crop',
  editorialSuit: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2000&auto=format&fit=crop',
  editorialStreet: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=2000&auto=format&fit=crop',
  shirtWhite: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1200&auto=format&fit=crop',
  shirtBlue: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1200&auto=format&fit=crop',
  shirtOxford: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1200&auto=format&fit=crop',
  shirtLinen: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?q=80&w=1200&auto=format&fit=crop',
  poloBlack: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?q=80&w=1200&auto=format&fit=crop',
  poloNavy: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?q=80&w=1200&auto=format&fit=crop',
  poloWhite: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?q=80&w=1200&auto=format&fit=crop',
  tshirtWhite: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1200&auto=format&fit=crop',
  tshirtBlack: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1200&auto=format&fit=crop',
  trousersChino: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=1200&auto=format&fit=crop',
  trousersFormal: 'https://images.unsplash.com/photo-1624206112918-f2f7f2c5b3e7?q=80&w=1200&auto=format&fit=crop',
  jeansBlue: 'https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=1200&auto=format&fit=crop',
  jeansBlack: 'https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=1200&auto=format&fit=crop',
  shortsChino: 'https://images.unsplash.com/photo-1591195854234-9c5b4eaaab7c?q=80&w=1200&auto=format&fit=crop',
  joggersBlack: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?q=80&w=1200&auto=format&fit=crop',
  blazerNavy: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200&auto=format&fit=crop',
  blazerCharcoal: 'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?q=80&w=1200&auto=format&fit=crop',
  suitCharcoal: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=1200&auto=format&fit=crop',
  jacketBomber: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1200&auto=format&fit=crop',
  jacketDenim: 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?q=80&w=1200&auto=format&fit=crop',
  hoodieGrey: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1200&auto=format&fit=crop',
  hoodieBlack: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1200&auto=format&fit=crop',
  shoesLoafer: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?q=80&w=1200&auto=format&fit=crop',
  shoesDress: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?q=80&w=1200&auto=format&fit=crop',
  shoesSneaker: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1200&auto=format&fit=crop',
  shoesCasual: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1200&auto=format&fit=crop',
  shoesExotic: 'https://images.unsplash.com/photo-1614253429340-98120bd6d753?q=80&w=1200&auto=format&fit=crop',
  sunglasses: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=1200&auto=format&fit=crop',
  beltLeather: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?q=80&w=1200&auto=format&fit=crop',
  capBlack: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?q=80&w=1200&auto=format&fit=crop',
  pocketSquare: 'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?q=80&w=1200&auto=format&fit=crop',
  tieSilk: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1200&auto=format&fit=crop',
  socksPack: 'https://images.unsplash.com/photo-1564859228273-274232fdb516?q=80&w=1200&auto=format&fit=crop',
  walletLeather: 'https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=1200&auto=format&fit=crop',
  fragranceMen: 'https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1200&auto=format&fit=crop',
  fragranceWomen: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1200&auto=format&fit=crop',
  groomingKit: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?q=80&w=1200&auto=format&fit=crop',
  beardOil: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1200&auto=format&fit=crop',
  pyjamas: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1200&auto=format&fit=crop',
  innerwear: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?q=80&w=1200&auto=format&fit=crop',
  ig1: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=800&auto=format&fit=crop',
  ig2: 'https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?q=80&w=800&auto=format&fit=crop',
  ig3: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=800&auto=format&fit=crop',
  ig4: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?q=80&w=800&auto=format&fit=crop',
  ig5: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop',
  ig6: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?q=80&w=800&auto=format&fit=crop',
}

const categories = [
  { name: 'New Arrivals', slug: 'new-arrivals', order: 1, featured: true },
  { name: 'Clothing', slug: 'clothing', order: 2, featured: true },
  { name: 'Bottoms', slug: 'bottoms', order: 3, featured: true },
  { name: 'Footwear', slug: 'footwear', order: 4, featured: true },
  { name: 'Accessories', slug: 'accessories', order: 5, featured: true },
  { name: 'Fragrance & Grooming', slug: 'fragrance-grooming', order: 6, featured: true },
  { name: 'Essentials', slug: 'essentials', order: 7, featured: false },
]

const subcategories = [
  { name: 'T-Shirts', slug: 't-shirts', parent: 'clothing', image: IMG.tshirtWhite },
  { name: 'Polo Shirts', slug: 'polo-shirts', parent: 'clothing', image: IMG.poloBlack },
  { name: 'Casual Shirts', slug: 'casual-shirts', parent: 'clothing', image: IMG.shirtOxford },
  { name: 'Formal / Office Shirts', slug: 'formal-shirts', parent: 'clothing', image: IMG.shirtWhite },
  { name: 'Blazers', slug: 'blazers', parent: 'clothing', image: IMG.blazerNavy },
  { name: 'Suits', slug: 'suits', parent: 'clothing', image: IMG.suitCharcoal },
  { name: 'Jackets', slug: 'jackets', parent: 'clothing', image: IMG.jacketBomber },
  { name: 'Hoodies & Sweatshirts', slug: 'hoodies-sweatshirts', parent: 'clothing', image: IMG.hoodieGrey },
  { name: 'Innerwear', slug: 'innerwear', parent: 'clothing', image: IMG.innerwear },
  { name: 'Chinos', slug: 'chinos', parent: 'bottoms', image: IMG.trousersChino },
  { name: 'Trousers', slug: 'trousers', parent: 'bottoms', image: IMG.trousersFormal },
  { name: 'Jeans', slug: 'jeans', parent: 'bottoms', image: IMG.jeansBlue },
  { name: 'Shorts', slug: 'shorts', parent: 'bottoms', image: IMG.shortsChino },
  { name: 'Joggers', slug: 'joggers', parent: 'bottoms', image: IMG.joggersBlack },
  { name: 'Casual Shoes', slug: 'casual-shoes', parent: 'footwear', image: IMG.shoesCasual },
  { name: 'Dress Shoes', slug: 'dress-shoes', parent: 'footwear', image: IMG.shoesDress },
  { name: 'Exotic Shoes', slug: 'exotic-shoes', parent: 'footwear', image: IMG.shoesExotic },
  { name: 'Loafers', slug: 'loafers', parent: 'footwear', image: IMG.shoesLoafer },
  { name: 'Sunglasses', slug: 'sunglasses', parent: 'accessories', image: IMG.sunglasses },
  { name: 'Belts', slug: 'belts', parent: 'accessories', image: IMG.beltLeather },
  { name: 'Caps & Hats', slug: 'caps-hats', parent: 'accessories', image: IMG.capBlack },
  { name: 'Pocket Squares', slug: 'pocket-squares', parent: 'accessories', image: IMG.pocketSquare },
  { name: 'Ties', slug: 'ties', parent: 'accessories', image: IMG.tieSilk },
  { name: 'Socks', slug: 'socks', parent: 'accessories', image: IMG.socksPack },
  { name: 'Wallets & Purses', slug: 'wallets-purses', parent: 'accessories', image: IMG.walletLeather },
  { name: "Men's Fragrance", slug: 'mens-fragrance', parent: 'fragrance-grooming', image: IMG.fragranceMen },
  { name: "Women's Fragrance", slug: 'womens-fragrance', parent: 'fragrance-grooming', image: IMG.fragranceWomen },
  { name: "Men's Grooming", slug: 'mens-grooming', parent: 'fragrance-grooming', image: IMG.groomingKit },
  { name: 'Pyjamas', slug: 'pyjamas', parent: 'essentials', image: IMG.pyjamas },
]

const sizesClothing = ['S', 'M', 'L', 'XL', 'XXL']
const sizesTrousers = ['30', '32', '34', '36', '38', '40']
const sizesShoes = ['40', '41', '42', '43', '44', '45']
const sizesFree = ['OS']

type ProductSeed = {
  name: string
  slug: string
  categorySlug: string
  description: string
  features?: string
  material?: string
  fit?: string
  care?: string
  sku: string
  price: number
  salePrice?: number
  images: string[]
  sizes: string[]
  stock: number
  featured?: boolean
  tags?: string
}

const products: ProductSeed[] = [
  {
    name: 'Classic Long-Sleeve Dress Shirt — White',
    slug: 'classic-long-sleeve-dress-shirt-white',
    categorySlug: 'formal-shirts',
    description: 'A crisp, tailored white dress shirt cut from breathable cotton with a refined spread collar. Engineered for the office, evenings, and occasions that demand a polished silhouette.',
    features: 'Spread collar • Rounded barrel cuffs • Mother-of-pearl buttons • Slim regular fit',
    material: '100% combed cotton, 120s weave',
    fit: 'Tailored — true to size',
    care: 'Machine wash cold. Iron warm.',
    sku: 'WC-SH-001',
    price: 18500,
    salePrice: 15500,
    images: [IMG.shirtWhite, IMG.shirtOxford, IMG.shirtBlue],
    sizes: sizesClothing,
    stock: 48,
    featured: true,
    tags: 'bestseller,formal,office',
  },
  {
    name: 'Oxford Casual Shirt — Sky Blue',
    slug: 'oxford-casual-shirt-sky-blue',
    categorySlug: 'casual-shirts',
    description: 'A relaxed Oxford-weave shirt in sky blue that bridges weekday polish with weekend ease. Soft hand-feel, button-down collar, and a versatile regular fit.',
    features: 'Button-down collar • Chest pocket • Single-needle stitching',
    material: '100% Oxford cotton',
    fit: 'Regular fit',
    care: 'Machine wash cold.',
    sku: 'WC-SH-002',
    price: 16500,
    images: [IMG.shirtBlue, IMG.shirtOxford],
    sizes: sizesClothing,
    stock: 35,
    featured: true,
    tags: 'casual,new',
  },
  {
    name: 'Linen Open-Collar Shirt — Sand',
    slug: 'linen-open-collar-shirt-sand',
    categorySlug: 'casual-shirts',
    description: 'An airy linen shirt with an open camp collar — built for warm Lagos afternoons and resort evenings. Lightweight, breathable, and effortlessly styled.',
    features: 'Open camp collar • Straight hem • Natural shell buttons',
    material: '100% European linen',
    fit: 'Relaxed fit',
    care: 'Gentle machine wash. Hang dry.',
    sku: 'WC-SH-003',
    price: 22000,
    images: [IMG.shirtLinen, IMG.shirtOxford],
    sizes: sizesClothing,
    stock: 22,
    tags: 'new,linen,resort',
  },
  {
    name: 'Premium Cotton Polo — Black',
    slug: 'premium-cotton-polo-black',
    categorySlug: 'polo-shirts',
    description: 'A refined piqué-knit polo in jet black. Tailored collar, durable ribbed cuffs, and a clean two-button placket — a wardrobe essential elevated in every detail.',
    features: 'Piqué cotton knit • Ribbed collar and cuffs • Two-button placket',
    material: '100% piqué cotton',
    fit: 'Tailored fit',
    care: 'Machine wash cold.',
    sku: 'WC-PO-001',
    price: 14500,
    images: [IMG.poloBlack, IMG.poloNavy],
    sizes: sizesClothing,
    stock: 60,
    featured: true,
    tags: 'bestseller,essential',
  },
  {
    name: 'Premium Cotton Polo — Navy',
    slug: 'premium-cotton-polo-navy',
    categorySlug: 'polo-shirts',
    description: 'The Wardrobecare polo in deep navy — versatile enough for the office on a Friday and refined enough for an evening out.',
    features: 'Piqué cotton knit • Ribbed collar and cuffs',
    material: '100% piqué cotton',
    fit: 'Tailored fit',
    care: 'Machine wash cold.',
    sku: 'WC-PO-002',
    price: 14500,
    images: [IMG.poloNavy, IMG.poloBlack],
    sizes: sizesClothing,
    stock: 40,
    tags: 'bestseller',
  },
  {
    name: 'Premium Cotton Polo — White',
    slug: 'premium-cotton-polo-white',
    categorySlug: 'polo-shirts',
    description: 'A clean white polo with a structured collar — the foundation of a curated summer wardrobe.',
    features: 'Piqué cotton knit • Ribbed collar and cuffs',
    material: '100% piqué cotton',
    fit: 'Tailored fit',
    care: 'Machine wash cold.',
    sku: 'WC-PO-003',
    price: 14500,
    images: [IMG.poloWhite, IMG.poloBlack],
    sizes: sizesClothing,
    stock: 38,
    tags: 'essential',
  },
  {
    name: 'Heavyweight Cotton Tee — Off-White',
    slug: 'heavyweight-cotton-tee-off-white',
    categorySlug: 't-shirts',
    description: 'A heavyweight 240gsm cotton tee with a clean round neckline and a structured shoulder. Built to hold its shape wash after wash.',
    features: '240gsm jersey • Reinforced shoulder • Pre-shrunk',
    material: '100% combed cotton',
    fit: 'Regular fit',
    care: 'Machine wash cold.',
    sku: 'WC-TS-001',
    price: 9500,
    images: [IMG.tshirtWhite, IMG.tshirtBlack],
    sizes: sizesClothing,
    stock: 80,
    featured: true,
    tags: 'essential,bestseller',
  },
  {
    name: 'Heavyweight Cotton Tee — Black',
    slug: 'heavyweight-cotton-tee-black',
    categorySlug: 't-shirts',
    description: 'The black counterpart to our off-white essential tee. A clean monochrome foundation for any outfit.',
    features: '240gsm jersey • Reinforced shoulder • Pre-shrunk',
    material: '100% combed cotton',
    fit: 'Regular fit',
    care: 'Machine wash cold.',
    sku: 'WC-TS-002',
    price: 9500,
    images: [IMG.tshirtBlack, IMG.tshirtWhite],
    sizes: sizesClothing,
    stock: 75,
    tags: 'essential',
  },
  {
    name: 'Tailored Wool-Blend Blazer — Navy',
    slug: 'tailored-wool-blend-blazer-navy',
    categorySlug: 'blazers',
    description: 'A structured navy blazer cut from a refined wool blend. Half-canvas construction, natural shoulder, and a clean two-button front — equally at home over a shirt or knit.',
    features: 'Half-canvas construction • Natural shoulder • Functional surgeon cuffs',
    material: '70% wool, 30% polyester',
    fit: 'Slim tailored fit',
    care: 'Dry clean only.',
    sku: 'WC-BL-001',
    price: 68000,
    salePrice: 58000,
    images: [IMG.blazerNavy, IMG.blazerCharcoal],
    sizes: sizesClothing,
    stock: 18,
    featured: true,
    tags: 'premium,formal',
  },
  {
    name: 'Two-Piece Suit — Charcoal',
    slug: 'two-piece-suit-charcoal',
    categorySlug: 'suits',
    description: 'A complete two-piece suit in charcoal — a slim-tailored jacket with matching flat-front trousers. Engineered for the wedding guest, the executive, and the man who simply dresses well.',
    features: 'Slim-tailored jacket • Flat-front trousers • Full Bemberg lining',
    material: 'Wool blend',
    fit: 'Slim fit',
    care: 'Dry clean only.',
    sku: 'WC-ST-001',
    price: 125000,
    salePrice: 105000,
    images: [IMG.suitCharcoal, IMG.blazerCharcoal],
    sizes: sizesClothing,
    stock: 10,
    featured: true,
    tags: 'premium,wedding,formal',
  },
  {
    name: 'Bomber Jacket — Olive',
    slug: 'bomber-jacket-olive',
    categorySlug: 'jackets',
    description: 'A modern bomber in olive — clean lines, ribbed trims, and a lightweight construction that layers cleanly through the seasons.',
    features: 'Ribbed collar and cuffs • YKK zip • Two welt pockets',
    material: 'Polyester-twill with cotton lining',
    fit: 'Regular fit',
    care: 'Machine wash cold.',
    sku: 'WC-JK-001',
    price: 32000,
    images: [IMG.jacketBomber, IMG.jacketDenim],
    sizes: sizesClothing,
    stock: 25,
    tags: 'new,casual',
  },
  {
    name: 'Heavyweight Hoodie — Heather Grey',
    slug: 'heavyweight-hoodie-heather-grey',
    categorySlug: 'hoodies-sweatshirts',
    description: 'A heavyweight fleece hoodie in heather grey with a structured hood and clean ribbed cuffs. The kind of hoodie that becomes a daily uniform.',
    features: '450gsm fleece • Double-lined hood • Kangaroo pocket',
    material: '80% cotton, 20% polyester',
    fit: 'Regular fit',
    care: 'Machine wash cold.',
    sku: 'WC-HD-001',
    price: 18500,
    images: [IMG.hoodieGrey, IMG.hoodieBlack],
    sizes: sizesClothing,
    stock: 45,
    featured: true,
    tags: 'essential,new',
  },
  {
    name: 'Heavyweight Hoodie — Black',
    slug: 'heavyweight-hoodie-black',
    categorySlug: 'hoodies-sweatshirts',
    description: 'The black counterpart to our heather-grey essential hoodie.',
    features: '450gsm fleece • Double-lined hood • Kangaroo pocket',
    material: '80% cotton, 20% polyester',
    fit: 'Regular fit',
    care: 'Machine wash cold.',
    sku: 'WC-HD-002',
    price: 18500,
    images: [IMG.hoodieBlack, IMG.hoodieGrey],
    sizes: sizesClothing,
    stock: 38,
    tags: 'essential',
  },
  {
    name: 'Stretch Cotton Chinos — Stone',
    slug: 'stretch-cotton-chinos-stone',
    categorySlug: 'chinos',
    description: 'Versatile stretch-cotton chinos in stone — a flat-front silhouette with a clean taper. Equally at home with a polo or a button-down.',
    features: '2% elastane for stretch • Flat front • Slant pockets',
    material: '98% cotton, 2% elastane',
    fit: 'Slim tapered fit',
    care: 'Machine wash cold.',
    sku: 'WC-CH-001',
    price: 19500,
    images: [IMG.trousersChino],
    sizes: sizesTrousers,
    stock: 42,
    featured: true,
    tags: 'bestseller',
  },
  {
    name: 'Wool-Blend Formal Trousers — Charcoal',
    slug: 'wool-blend-formal-trousers-charcoal',
    categorySlug: 'trousers',
    description: 'A polished wool-blend trouser in charcoal with a clean straight leg. Cut for the office, refined enough for evenings.',
    features: 'French fly closure • Side pockets',
    material: 'Wool blend',
    fit: 'Straight fit',
    care: 'Dry clean recommended.',
    sku: 'WC-TR-001',
    price: 26000,
    images: [IMG.trousersFormal],
    sizes: sizesTrousers,
    stock: 24,
    tags: 'formal,office',
  },
  {
    name: 'Slim-Fit Denim Jeans — Indigo',
    slug: 'slim-fit-denim-jeans-indigo',
    categorySlug: 'jeans',
    description: 'A premium slim-fit denim in deep indigo. Refined enough to dress up with a blazer, easy enough for everyday wear.',
    features: 'Five-pocket design • Mid-rise • Stretch comfort',
    material: '98% cotton, 2% elastane',
    fit: 'Slim fit',
    care: 'Machine wash cold inside out.',
    sku: 'WC-JN-001',
    price: 22000,
    images: [IMG.jeansBlue, IMG.jeansBlack],
    sizes: sizesTrousers,
    stock: 50,
    featured: true,
    tags: 'bestseller',
  },
  {
    name: 'Slim-Fit Denim Jeans — Black',
    slug: 'slim-fit-denim-jeans-black',
    categorySlug: 'jeans',
    description: 'A black denim counterpart with the same engineered slim fit. Sharp, versatile, and built to fade slowly.',
    features: 'Five-pocket design • Mid-rise • Stretch comfort',
    material: '98% cotton, 2% elastane',
    fit: 'Slim fit',
    care: 'Machine wash cold inside out.',
    sku: 'WC-JN-002',
    price: 22000,
    images: [IMG.jeansBlack, IMG.jeansBlue],
    sizes: sizesTrousers,
    stock: 32,
    tags: 'essential',
  },
  {
    name: 'Tailored Chino Shorts — Khaki',
    slug: 'tailored-chino-shorts-khaki',
    categorySlug: 'shorts',
    description: 'A clean chino short in khaki with a 7-inch inseam. Tailored enough to look intentional, relaxed enough for the weekend.',
    features: '7-inch inseam • Flat front • Slant pockets',
    material: '98% cotton, 2% elastane',
    fit: 'Slim fit',
    care: 'Machine wash cold.',
    sku: 'WC-SH-RT-001',
    price: 13500,
    images: [IMG.shortsChino],
    sizes: sizesTrousers,
    stock: 28,
    tags: 'new,seasonal',
  },
  {
    name: 'Tapered Joggers — Black',
    slug: 'tapered-joggers-black',
    categorySlug: 'joggers',
    description: 'A premium taper-leg jogger in black with ribbed cuffs and a clean drawstring waist. The refined answer to off-duty comfort.',
    features: 'Ribbed cuffs • Drawstring waist • Zip pockets',
    material: 'French terry cotton',
    fit: 'Tapered fit',
    care: 'Machine wash cold.',
    sku: 'WC-JG-001',
    price: 16500,
    images: [IMG.joggersBlack],
    sizes: sizesTrousers,
    stock: 30,
    tags: 'essential,casual',
  },
  {
    name: 'Hand-Stitched Penny Loafers — Brown',
    slug: 'hand-stitched-penny-loafers-brown',
    categorySlug: 'loafers',
    description: 'A hand-stitched penny loafer in polished brown leather with a leather sole. A wardrobe cornerstone — equally at home with denim or tailored trousers.',
    features: 'Genuine leather upper • Leather sole • Hand-stitched apron',
    material: 'Full-grain leather',
    fit: 'True to size',
    care: 'Polish regularly with shoe trees.',
    sku: 'WC-FW-001',
    price: 48000,
    salePrice: 42000,
    images: [IMG.shoesLoafer, IMG.shoesDress],
    sizes: sizesShoes,
    stock: 20,
    featured: true,
    tags: 'premium,bestseller',
  },
  {
    name: 'Oxford Dress Shoes — Black',
    slug: 'oxford-dress-shoes-black',
    categorySlug: 'dress-shoes',
    description: 'A clean cap-toe Oxford in black leather. The definitive formal shoe — for the office, the wedding, the occasion.',
    features: 'Cap-toe construction • Goodyear-welted • Leather sole',
    material: 'Calf leather',
    fit: 'True to size',
    care: 'Polish regularly.',
    sku: 'WC-FW-002',
    price: 56000,
    images: [IMG.shoesDress, IMG.shoesLoafer],
    sizes: sizesShoes,
    stock: 15,
    featured: true,
    tags: 'formal,premium',
  },
  {
    name: 'Minimal Leather Sneakers — White',
    slug: 'minimal-leather-sneakers-white',
    categorySlug: 'casual-shoes',
    description: 'A minimal white leather sneaker with a clean cup-sole and a tonal lace. Quietly luxurious — the kind of sneaker that improves with age.',
    features: 'Full-grain leather upper • Cushioned insole • Vulcanised cup-sole',
    material: 'Full-grain leather',
    fit: 'True to size',
    care: 'Wipe clean. Use leather conditioner.',
    sku: 'WC-FW-003',
    price: 38000,
    images: [IMG.shoesSneaker, IMG.shoesCasual],
    sizes: sizesShoes,
    stock: 35,
    featured: true,
    tags: 'bestseller,new',
  },
  {
    name: 'Suede Exotic Monk-Strap — Cognac',
    slug: 'suede-exotic-monk-strap-cognac',
    categorySlug: 'exotic-shoes',
    description: "A single-monk strap in soft cognac suede with a polished leather sole. Distinctive without being loud — the connoisseur's choice.",
    features: 'Single-monk strap • Suede upper • Leather sole',
    material: 'Suede and full-grain leather',
    fit: 'True to size',
    care: 'Brush suede regularly. Use shoe trees.',
    sku: 'WC-FW-004',
    price: 62000,
    images: [IMG.shoesExotic, IMG.shoesLoafer],
    sizes: sizesShoes,
    stock: 12,
    tags: 'premium,exotic',
  },
  {
    name: 'Classic Aviator Sunglasses — Gold / Green',
    slug: 'classic-aviator-sunglasses-gold-green',
    categorySlug: 'sunglasses',
    description: 'A timeless aviator silhouette in gold with green-tinted lenses. UV400 protection in an iconically cool frame.',
    features: 'UV400 protection • Metal frame • Adjustable nose pads',
    material: 'Metal frame, glass lens',
    fit: 'One size',
    care: 'Store in case. Clean with microfibre.',
    sku: 'WC-AC-001',
    price: 12500,
    images: [IMG.sunglasses],
    sizes: sizesFree,
    stock: 45,
    tags: 'essential',
  },
  {
    name: 'Full-Grain Leather Belt — Brown',
    slug: 'full-grain-leather-belt-brown',
    categorySlug: 'belts',
    description: 'A full-grain leather belt in brown with a brushed silver buckle. The kind of belt that develops a beautiful patina over years.',
    features: 'Full-grain leather • Solid brass buckle • 35mm width',
    material: 'Full-grain leather',
    fit: 'True to size — order trouser size',
    care: 'Condition leather periodically.',
    sku: 'WC-AC-002',
    price: 11500,
    images: [IMG.beltLeather],
    sizes: sizesTrousers,
    stock: 50,
    tags: 'essential',
  },
  {
    name: 'Structured Cotton Cap — Black',
    slug: 'structured-cotton-cap-black',
    categorySlug: 'caps-hats',
    description: 'A clean six-panel cap in black with a curved brim and a tonal embroidered Wardrobecare mark.',
    features: 'Six-panel construction • Curved brim • Metal adjustor',
    material: '100% cotton twill',
    fit: 'Adjustable',
    care: 'Spot clean.',
    sku: 'WC-AC-003',
    price: 7500,
    images: [IMG.capBlack],
    sizes: sizesFree,
    stock: 60,
    tags: 'new',
  },
  {
    name: 'Silk Pocket Square — Burgundy',
    slug: 'silk-pocket-square-burgundy',
    categorySlug: 'pocket-squares',
    description: 'A silk pocket square in deep burgundy with a hand-rolled edge. The quiet detail that elevates a blazer.',
    features: 'Hand-rolled edge • 30cm × 30cm',
    material: '100% silk',
    fit: 'One size',
    care: 'Dry clean only.',
    sku: 'WC-AC-004',
    price: 6500,
    images: [IMG.pocketSquare],
    sizes: sizesFree,
    stock: 40,
    tags: 'formal',
  },
  {
    name: 'Silk Tie — Midnight Navy',
    slug: 'silk-tie-midnight-navy',
    categorySlug: 'ties',
    description: 'A silk tie in midnight navy with a subtle woven texture. The right amount of formality, never loud.',
    features: '7cm blade • Hand-finished tipping',
    material: '100% silk',
    fit: 'One size',
    care: 'Dry clean only.',
    sku: 'WC-AC-005',
    price: 9500,
    images: [IMG.tieSilk],
    sizes: sizesFree,
    stock: 35,
    tags: 'formal',
  },
  {
    name: 'Cotton Crew Socks — Three-Pack',
    slug: 'cotton-crew-socks-three-pack',
    categorySlug: 'socks',
    description: 'A three-pack of combed cotton crew socks in tonal neutrals. Reinforced heel and toe, breathable mesh upper.',
    features: 'Reinforced heel and toe • Seamless toe • Combed cotton',
    material: '80% cotton, 18% polyamide, 2% elastane',
    fit: 'EU 40–45',
    care: 'Machine wash warm.',
    sku: 'WC-AC-006',
    price: 8500,
    images: [IMG.socksPack],
    sizes: sizesFree,
    stock: 70,
    tags: 'essential',
  },
  {
    name: 'Bifold Leather Wallet — Cognac',
    slug: 'bifold-leather-wallet-cognac',
    categorySlug: 'wallets-purses',
    description: 'A slim bifold wallet in cognac full-grain leather with six card slots and a full-length note pocket.',
    features: 'Six card slots • Full-length note pocket • Slim profile',
    material: 'Full-grain leather',
    fit: 'One size',
    care: 'Condition leather periodically.',
    sku: 'WC-AC-007',
    price: 14500,
    images: [IMG.walletLeather, IMG.beltLeather],
    sizes: sizesFree,
    stock: 32,
    tags: 'premium,new',
  },
  {
    name: 'Eau de Parfum — Oud & Amber',
    slug: 'eau-de-parfum-oud-amber',
    categorySlug: 'mens-fragrance',
    description: "A sophisticated men's Eau de Parfum built on oud, amber, and warm spice. Long-lasting and quietly distinctive.",
    features: '100ml • EDP concentration • Long-lasting projection',
    material: 'Oud, amber, bergamot, cedarwood',
    fit: 'One size',
    care: 'Store away from direct sunlight.',
    sku: 'WC-FR-001',
    price: 35000,
    images: [IMG.fragranceMen, IMG.fragranceWomen],
    sizes: sizesFree,
    stock: 28,
    featured: true,
    tags: 'premium,new',
  },
  {
    name: 'Eau de Parfum — Rose & Musk',
    slug: 'eau-de-parfum-rose-musk',
    categorySlug: 'womens-fragrance',
    description: "A women's Eau de Parfum built on rose, white musk, and a soft vanilla drydown. Elegant, modern, and warm.",
    features: '100ml • EDP concentration • Soft sillage',
    material: 'Bulgarian rose, white musk, vanilla',
    fit: 'One size',
    care: 'Store away from direct sunlight.',
    sku: 'WC-FR-002',
    price: 35000,
    images: [IMG.fragranceWomen, IMG.fragranceMen],
    sizes: sizesFree,
    stock: 22,
    tags: 'new',
  },
  {
    name: 'Beard Grooming Kit',
    slug: 'beard-grooming-kit',
    categorySlug: 'mens-grooming',
    description: 'A complete beard grooming kit — beard oil, beard balm, moustache wax, and a boar-bristle brush. The essentials, curated.',
    features: 'Beard oil 30ml • Beard balm 50g • Moustache wax • Boar-bristle brush',
    material: 'Natural oils and butters',
    fit: 'One size',
    care: 'Store in a cool dry place.',
    sku: 'WC-GR-001',
    price: 18500,
    images: [IMG.groomingKit, IMG.beardOil],
    sizes: sizesFree,
    stock: 25,
    featured: true,
    tags: 'new,gift',
  },
  {
    name: 'Cedarwood Beard Oil — 30ml',
    slug: 'cedarwood-beard-oil-30ml',
    categorySlug: 'mens-grooming',
    description: 'A lightweight beard oil with cedarwood, argan, and jojoba. Conditions hair and skin without leaving residue.',
    features: '30ml dropper bottle • Lightweight • Non-greasy',
    material: 'Argan, jojoba, cedarwood essential oil',
    fit: 'One size',
    care: 'Use 2–3 drops daily.',
    sku: 'WC-GR-002',
    price: 7500,
    images: [IMG.beardOil, IMG.groomingKit],
    sizes: sizesFree,
    stock: 55,
    tags: 'essential',
  },
  {
    name: 'Soft-Cotton Pyjama Set — Charcoal',
    slug: 'soft-cotton-pyjama-set-charcoal',
    categorySlug: 'pyjamas',
    description: 'A soft-cotton pyjama set in charcoal with a notched collar and a clean piped trim. Quietly refined loungewear.',
    features: 'Notched collar • Piped trim • Elastic waist with drawstring',
    material: '100% brushed cotton',
    fit: 'Regular fit',
    care: 'Machine wash cold.',
    sku: 'WC-ES-001',
    price: 16500,
    images: [IMG.pyjamas],
    sizes: sizesClothing,
    stock: 28,
    tags: 'essential,new',
  },
]

const faqs = [
  { question: 'How do I place an order?', answer: 'Browse the catalogue, add items to your bag, and proceed to checkout. You can pay securely online via Paystack or order via WhatsApp for a personal-shopping experience.', category: 'Orders' },
  { question: 'Can I order via WhatsApp?', answer: 'Yes. Use the "Order via WhatsApp" button on any product page or in checkout. Our team will confirm availability, share payment details, and arrange delivery.', category: 'Orders' },
  { question: 'Which payment methods do you accept?', answer: 'We accept Paystack (cards, bank transfer, USSD) and bank transfer. All online payments are verified server-side before an order is marked as paid.', category: 'Payments' },
  { question: 'How long does delivery take?', answer: 'Lagos deliveries typically arrive within 1–2 business days. Other states arrive within 2–5 business days depending on location.', category: 'Shipping' },
  { question: 'What is your return policy?', answer: 'Unworn items in original packaging can be returned within 7 days of delivery. Sale items are final sale. See our Returns page for full details.', category: 'Returns' },
  { question: 'Do you ship outside Nigeria?', answer: 'We currently ship within Nigeria. For international delivery requests, please contact us via WhatsApp.', category: 'Shipping' },
  { question: 'How do I track my order?', answer: 'Visit the Order Tracking page and enter your order number. You will see the current status and tracking information once your order has been shipped.', category: 'Orders' },
  { question: 'Are the products true to size?', answer: 'Each product page includes fit guidance. If you are between sizes, our team is available via WhatsApp to advise on the right fit.', category: 'Products' },
]

async function main() {
  console.log('🌱 Seeding Wardrobecare database...')

  console.log('→ Creating categories...')
  for (const c of categories) {
    await db.category.upsert({
      where: { slug: c.slug },
      update: {},
      create: { name: c.name, slug: c.slug, order: c.order, featured: c.featured },
    })
  }
  for (const s of subcategories) {
    const parent = await db.category.findUnique({ where: { slug: s.parent } })
    if (!parent) continue
    await db.category.upsert({
      where: { slug: s.slug },
      update: { image: s.image },
      create: { name: s.name, slug: s.slug, parentId: parent.id, image: s.image },
    })
  }

  console.log('→ Creating admin user...')
  const adminEmail = 'admin@wardrobecare.com'
  const existingAdmin = await db.user.findUnique({ where: { email: adminEmail } })
  if (!existingAdmin) {
    const passwordHash = await bcrypt.hash('wardrobecare2026', 10)
    await db.user.create({
      data: {
        email: adminEmail,
        name: 'Wardrobecare Admin',
        phone: '+2348000000000',
        role: 'ADMIN',
        passwordHash,
      },
    })
    console.log(`  ✓ Admin: ${adminEmail} / wardrobecare2026`)
  }

  console.log('→ Creating products...')
  for (const p of products) {
    const category = await db.category.findUnique({ where: { slug: p.categorySlug } })
    if (!category) { console.warn(`  ⚠ Category not found for ${p.slug}`); continue }
    const existing = await db.product.findUnique({ where: { slug: p.slug } })
    if (existing) continue
    await db.product.create({
      data: {
        name: p.name,
        slug: p.slug,
        description: p.description,
        features: p.features,
        material: p.material,
        fit: p.fit,
        care: p.care,
        sku: p.sku,
        price: p.price,
        salePrice: p.salePrice,
        categoryId: category.id,
        tags: p.tags,
        featured: p.featured ?? false,
        published: true,
        images: { create: p.images.map((url, i) => ({ url, altText: p.name, position: i })) },
        variants: {
          create: p.sizes.map((size) => ({
            size,
            sku: `${p.sku}-${size}`,
            stock: Math.floor(p.stock / p.sizes.length),
            lowStockThreshold: 5,
            imageUrl: p.images[0],
          })),
        },
      },
    })
  }

  console.log('→ Creating homepage content...')
  await db.homepageContent.upsert({
    where: { id: 'singleton' },
    update: {},
    create: {
      id: 'singleton',
      heroTitle: 'A service built around your style.',
      heroSubtitle:
        'Personal shopping, wardrobe consultations, home fittings and more — guided by a real stylist, built around how you live and dress.',
      heroPrimaryCta: 'EXPLORE SERVICES',
      heroPrimaryHref: '/services',
      heroSecondaryCta: 'SHOP PIECES',
      heroSecondaryHref: '/shop',
      heroImage: IMG.heroEditorial,
      heroImageAlt: 'A service built around your style — Wardrobecare editorial',
      featuredImage: IMG.editorialSuit,
      instagramImages: JSON.stringify([IMG.ig1, IMG.ig2, IMG.ig3, IMG.ig4, IMG.ig5, IMG.ig6]),
    },
  })

  console.log('→ Creating admin settings...')
  await db.adminSettings.upsert({
    where: { id: 'singleton' },
    update: {},
    create: {
      id: 'singleton',
      whatsappNumber: '2348000000000',
      whatsappEnabled: true,
      instagramUrl: 'https://www.instagram.com/wardrobecareng/',
      storeName: 'Wardrobecare Clothing',
      storeTagline: "Your #1 Personal Shopper for premium men's fashion.",
      defaultDeliveryFee: 2500,
      freeDeliveryThreshold: 50000,
    },
  })

  console.log('→ Creating FAQs...')
  for (const f of faqs) {
    const existing = await db.fAQ.findFirst({ where: { question: f.question } })
    if (!existing) { await db.fAQ.create({ data: f }) }
  }

  console.log('→ Creating promotional banner...')
  await db.promotionalBanner.upsert({
    where: { id: 'singleton-banner' },
    update: {},
    create: {
      id: 'singleton-banner',
      title: 'New Season — Now Arriving',
      subtitle: 'Premium menswear, curated for the modern wardrobe.',
      image: IMG.heroFashion,
      ctaText: 'Shop New Arrivals',
      ctaHref: '/shop?sort=newest',
      active: true,
      order: 1,
    },
  })

  console.log('✅ Seed complete.')
  console.log(`   Admin login: admin@wardrobecare.com / wardrobecare2026`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await db.$disconnect() })
